### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by xermicus** [furunkel/libevoasm#1]
Hi, is there any documentation available? I want to use libevoasm (C library), but can't find any docs (the link in the ruby frontend is dead: https://evoasm.github.io/evoasm/doc/).

**Comment by furunkel** [comment]
The repo name is evoasm.rb now. Please see https://evoasm.github.io/evoasm.rb/doc/.
Also, libevoasm is useless without the frontend. You should have a look at the [evoasm.rb](https://github.com/evoasm/evoasm.rb) repository.
BTW, I've started porting the whole project to Kotlin (the x64 encoder and execution engine is mostly [finished](https://github.com/evoasm/kasm); this means the old C/Ruby stuff is no longer worked on (but should be fully functional and nice to play with).

**Comment by xermicus** [comment]
Thanks for your answer and the link! I'm planning to use the C library in rust and already have my input/output sets, so I think I'm going to stick to it.

**Comment by furunkel** [comment]
I see. You might want to look at the Ruby code then to see how to interface the backend.
